version: "3"

services:
  db:
      image: postgres
      ports:
          - 5432:5432
      env_file:
          - ./django/.env       
  
  dj:
    container_name: dj
    build: django
    command: python manage.py runserver 0.0.0.0:80
    volumes:
      - ./django:/code
    ports:
      - "80:80"
    depends_on:
      - db
  dj:
    container_name: dj
    build: django
    command: python manage.py runserver 0.0.0.0:80
    volumes:
      - ./django:/code
    ports:
      - "80:80"
    depends_on:
      - db
